site_name: Basic MkDocs Example Project

theme:
  name: material
  # logo : assets/logo.png
  # favicon: assets/logo.png
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [readthedocs_demo]
